### ISSUE TITLE
incorrect line endings in bin/semver-tags

### ISSUE THREAD

**Issue by jtrinklein** [jtrussell/semver-tags#9]
The line endings in `bin/semver-tags` are windows style line endings which causes an error when trying to run under a linux environment. this file needs to be converted to use linux line endings.
![screen shot 2017-08-31 at 11 26 35 am](https://user-images.githubusercontent.com/1398935/29939140-c3b084be-8e3f-11e7-9dc6-c8a2a9002c3b.png)

**Comment by jtrussell** [comment]
Ach, sorry. Bitten by https://github.com/npm/npm/issues/2097.

Should be good in 0.4.9

**Comment by jtrinklein** [comment]
Thanks!
